#Requires -Version 7.0

<#
.SYNOPSIS
    Example script demonstrating PowerSchool contact change submission.

.DESCRIPTION
    This script submits contact changes to PowerSchool using a change file generated
    by Example-ContactChangeDetection.ps1. It's a simple wrapper around the
    Submit-PSContactChange function.
    
    Prerequisites:
    - PowerSchool API credentials set in environment variables:
      * PowerSchool_BaseUrl
      * PowerSchool_ClientID
      * PowerSchool_ClientSecret
    - Change file generated by Example-ContactChangeDetection.ps1
    
.PARAMETER ChangeFilePath
    Path to the JSON file containing the detected changes.

.PARAMETER MaxRetries
    Maximum number of retries for failed API calls. Default: 3

.PARAMETER Limit
    Maximum number of changes to process in this run. Default: All changes
    Useful for testing with small batches.

.EXAMPLE
    .\Example-ContactSubmitChanges.ps1 -ChangeFilePath './data/pending/2026-01-31-1234-contact-changes.json'

.EXAMPLE
    # Process only first 5 changes for testing
    .\Example-ContactSubmitChanges.ps1 -ChangeFilePath './data/pending/2026-01-31-1234-contact-changes.json' -Limit 5

.EXAMPLE
    # Preview changes without applying (WhatIf mode)
    .\Example-ContactSubmitChanges.ps1 -ChangeFilePath './data/pending/2026-01-31-1234-contact-changes.json' -WhatIf

.NOTES
    This is a simple example wrapper. For production use, consider adding:
    - State tracking to resume after failures
    - Batch processing with pauses
    - Email notifications
    - Custom error handling
#>

param(
    [Parameter(Mandatory = $true)]
    [ValidateScript({ Test-Path $_ })]
    [string]$ChangeFilePath,
    
    [Parameter(Mandatory = $false)]
    [ValidateRange(1, 10)]
    [int]$MaxRetries = 3,
    
    [Parameter(Mandatory = $false)]
    [ValidateRange(1, [int]::MaxValue)]
    [int]$Limit = [int]::MaxValue
)

# Import the module
Import-Module (Join-Path $PSScriptRoot '../fsenrollment-pssync/FSEnrollment-PSSync.psd1') -Force

try {
    Write-Host "=== PowerSchool Contact Change Submission ===" -ForegroundColor Cyan
    Write-Host ""
    
    # Step 1: Connect to PowerSchool
    Write-Host "[1/2] Connecting to PowerSchool..." -ForegroundColor Yellow
    Connect-PowerSchool
    Write-Host "  ✓ Connected successfully" -ForegroundColor Green
    Write-Host ""
    
    # Step 2: Submit changes
    Write-Host "[2/2] Submitting changes to PowerSchool..." -ForegroundColor Yellow
    Write-Host "  Change file: $ChangeFilePath" -ForegroundColor Gray
    Write-Host "  Max retries: $MaxRetries" -ForegroundColor Gray
    if ($Limit -lt [int]::MaxValue) {
        Write-Host "  Limit: $Limit changes" -ForegroundColor Gray
    }
    Write-Host ""
    
    # Call Submit-PSContactChange with the change file
    Submit-PSContactChange -JsonPath $ChangeFilePath -MaxRetries $MaxRetries -Limit $Limit -Verbose:$VerbosePreference
    
    Write-Host ""
    Write-Host "Done!" -ForegroundColor Green
}
catch {
    Write-Host ""
    Write-Host "ERROR: $_" -ForegroundColor Red
    Write-Host "Stack Trace:" -ForegroundColor Red
    Write-Host $_.ScriptStackTrace -ForegroundColor Red
    exit 1
}
