function ConvertTo-ContactChangesCsv {
    <#
.SYNOPSIS
    Converts a PowerSchool contact changes JSON file to a CSV summary file.

.DESCRIPTION
    This function takes a contact changes JSON file (generated by Compare-PSContact or 
    Example-ContactChangeDetection.ps1) and converts it to a readable CSV file showing
    all individual field changes with old and new values.
    
    The CSV includes separate rows for each changed field, making it easy to review
    changes in Excel or other spreadsheet applications.

.PARAMETER JsonPath
    Path to the contact changes JSON file to convert.

.PARAMETER OutputPath
    Path where the CSV file will be saved. If not specified, creates a file with
    the same name as the JSON file but with a -summary.csv suffix.

.EXAMPLE
    ConvertTo-ContactChangesCsv -JsonPath './data/pending/2026-02-16-1402-contact-changes.json'
    
    Converts the JSON file to a CSV summary with default output path.

.EXAMPLE
    ConvertTo-ContactChangesCsv -JsonPath './data/pending/changes.json' -OutputPath './reports/changes.csv'
    
    Converts the JSON file to a CSV summary at the specified output path.

.OUTPUTS
    System.String
    Returns the path to the created CSV file.

.NOTES
    Each row in the CSV represents a single field change and includes:
    - ChangeCategory: 'New' or 'Updated'
    - ChangeType: Specific type (NewContact, EmailAdded, PhoneModified, etc.)
    - ContactIdentifier: Unique ID for the contact
    - ContactID: PowerSchool person_id (if exists)
    - FirstName, MiddleName, LastName: Contact name
    - Field: Which field changed
    - OldValue: Previous value (empty for new items)
    - NewValue: New value (empty for removed items)
    - StudentNumbers: Related student numbers (for relationships)
    - RecordID: PowerSchool ID for the related record (email, phone, address, or relationship)
    - RecordIDType: Type of ID (ContactID, EmailAddressID, PhoneNumberID, AddressID, StudentContactID)
#>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateScript({ Test-Path $_ })]
        [string]$JsonPath,
        
        [Parameter(Mandatory = $false)]
        [string]$OutputPath
    )
    
    try {
        # Determine output path if not specified
        if (-not $OutputPath) {
            $jsonFile = Get-Item $JsonPath
            $OutputPath = Join-Path $jsonFile.DirectoryName ($jsonFile.BaseName + '-summary.csv')
        }
        
        Write-Verbose "Reading JSON file: $JsonPath"
        $json = Get-Content $JsonPath -Raw | ConvertFrom-Json
        
        # Create array to hold CSV rows
        $csvData = [System.Collections.Generic.List[PSCustomObject]]::new()
        
        # Process New contacts
        Write-Verbose "Processing $($json.New.Count) new contacts..."
        foreach ($item in $json.New) {
            $csvData.Add((New-CsvRow -BaseData @{
                ChangeCategory = 'New'
                ChangeType = 'NewContact'
                ContactIdentifier = $item.Contact.ContactIdentifier
                ContactID = $item.Contact.ContactID
                FirstName = $item.Contact.FirstName
                MiddleName = $item.Contact.MiddleName
                LastName = $item.Contact.LastName
                Field = 'EntireContact'
                OldValue = ''
                NewValue = "New contact with $($item.EmailAddresses.Count) emails, $($item.PhoneNumbers.Count) phones, $($item.Addresses.Count) addresses"
                StudentNumbers = ($item.Relationships.StudentNumber -join '; ')
            }))
        }
        
        # Process Updated contacts
        Write-Verbose "Processing $($json.Updated.Count) updated contacts..."
        foreach ($item in $json.Updated) {
            $contactId = $item.MatchKey
            
            # Get contact name and ID - prefer CsvContact, fallback to PowerSchoolPerson
            $firstName = Get-PropertyValue $item.CsvContact 'FirstName' $item.PowerSchoolPerson 'person_firstname'
            $middleName = Get-PropertyValue $item.CsvContact 'MiddleName' $item.PowerSchoolPerson 'person_middlename'
            $lastName = Get-PropertyValue $item.CsvContact 'LastName' $item.PowerSchoolPerson 'person_lastname'
            $psContactId = Get-PropertyValue $item.PowerSchoolPerson '_id'
            
            # Base data for all rows from this contact
            $baseData = @{
                ContactIdentifier = $contactId
                ContactID = $psContactId
                FirstName = $firstName
                MiddleName = $middleName
                LastName = $lastName
            }
            
            # Contact demographic field changes (firstName, lastName, employer, etc.)
            if ($item.Changes) {
                # Handle both single change object and array of changes
                $changes = if ($item.Changes -is [array]) { $item.Changes } else { @($item.Changes) }
                
                foreach ($change in $changes) {
                    $csvData.Add((New-CsvRow -BaseData $baseData -ChangeData @{
                        ChangeCategory = 'Updated'
                        ChangeType = 'DemographicChanged'
                        Field = $change.Field
                        OldValue = $change.OldValue
                        NewValue = $change.NewValue
                    }))
                }
            }
            
            # Process all entity changes using generic handler
            Add-EntityChanges -CsvData $csvData -BaseData $baseData -EntityType 'Email' -Changes $item.EmailChanges
            Add-EntityChanges -CsvData $csvData -BaseData $baseData -EntityType 'Phone' -Changes $item.PhoneChanges
            Add-EntityChanges -CsvData $csvData -BaseData $baseData -EntityType 'Address' -Changes $item.AddressChanges
            Add-EntityChanges -CsvData $csvData -BaseData $baseData -EntityType 'Relationship' -Changes $item.RelationshipChanges
        }
        
        # Export to CSV
        Write-Verbose "Exporting $($csvData.Count) change rows to CSV..."
        $csvData | Export-Csv -Path $OutputPath -NoTypeInformation -Force
        
        Write-Host "CSV file created: $OutputPath" -ForegroundColor Green
        Write-Host "Total change rows: $($csvData.Count)" -ForegroundColor Cyan
        
        # Show change type breakdown
        if ($VerbosePreference -eq 'Continue') {
            Write-Host "`nChange type breakdown:" -ForegroundColor Yellow
            $csvData | Group-Object ChangeType | Sort-Object Count -Descending | ForEach-Object {
                Write-Host "  $($_.Name): $($_.Count)" -ForegroundColor Gray
            }
        }
        
        return $OutputPath
    }
    catch {
        Write-Error "Failed to convert JSON to CSV: $_"
        throw
    }
}

#region Private Helper Functions

<#
.SYNOPSIS
    Creates a new CSV row with all standard columns.

.DESCRIPTION
    Private helper function that creates a PSCustomObject with all CSV columns,
    ensuring consistency across all rows. Columns not provided are set to empty strings.

.PARAMETER BaseData
    Hashtable containing base contact information (ContactIdentifier, FirstName, etc.)

.PARAMETER ChangeData
    Optional hashtable containing change-specific information (ChangeType, Field, OldValue, etc.)

.OUTPUTS
    PSCustomObject with all CSV columns defined
#>
function New-CsvRow {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [hashtable]$BaseData,
        
        [Parameter(Mandatory = $false)]
        [hashtable]$ChangeData = @{}
    )
    
    # Merge BaseData and ChangeData, with ChangeData taking precedence
    $allData = $BaseData + $ChangeData
    
    # Create row with all columns (ensures consistent column order and presence)
    return [PSCustomObject]@{
        ChangeCategory = Get-HashValue $allData 'ChangeCategory'
        ChangeType = Get-HashValue $allData 'ChangeType'
        ContactIdentifier = Get-HashValue $allData 'ContactIdentifier'
        ContactID = Get-HashValue $allData 'ContactID'
        FirstName = Get-HashValue $allData 'FirstName'
        MiddleName = Get-HashValue $allData 'MiddleName'
        LastName = Get-HashValue $allData 'LastName'
        Field = Get-HashValue $allData 'Field'
        OldValue = Get-HashValue $allData 'OldValue'
        NewValue = Get-HashValue $allData 'NewValue'
        StudentNumbers = Get-HashValue $allData 'StudentNumbers'
        RecordID = Get-HashValue $allData 'RecordID'
        RecordIDType = Get-HashValue $allData 'RecordIDType'
    }
}

<#
.SYNOPSIS
    Safely gets a value from a hashtable, returning empty string if not found.
#>
function Get-HashValue {
    param([hashtable]$Hash, [string]$Key)
    if ($Hash.ContainsKey($Key) -and $null -ne $Hash[$Key]) {
        return $Hash[$Key]
    }
    return ''
}

<#
.SYNOPSIS
    Gets property value from object with fallback options.

.DESCRIPTION
    Tries to get a property value from the primary object. If not found or null,
    falls back to secondary object with optional different property name.

.PARAMETER Primary
    Primary object to check first

.PARAMETER PrimaryProp
    Property name in primary object

.PARAMETER Secondary
    Optional secondary object for fallback

.PARAMETER SecondaryProp
    Optional property name in secondary object (defaults to PrimaryProp)
#>
function Get-PropertyValue {
    param(
        [Parameter(Mandatory = $false)]
        $Primary,
        
        [Parameter(Mandatory = $true)]
        [string]$PrimaryProp,
        
        [Parameter(Mandatory = $false)]
        $Secondary,
        
        [Parameter(Mandatory = $false)]
        [string]$SecondaryProp
    )
    
    # Try primary object first
    if ($Primary -and $Primary.PSObject.Properties[$PrimaryProp]) {
        $value = $Primary.$PrimaryProp
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            return $value
        }
    }
    
    # Fall back to secondary object
    if ($Secondary -and $SecondaryProp) {
        if ($Secondary.PSObject.Properties[$SecondaryProp]) {
            $value = $Secondary.$SecondaryProp
            if (-not [string]::IsNullOrWhiteSpace($value)) {
                return $value
            }
        }
    }
    
    return ''
}

<#
.SYNOPSIS
    Formats phone number display with type, avoiding empty parentheses.
#>
function Format-PhoneDisplay {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PhoneNumber,
        
        [Parameter(Mandatory = $false)]
        [string]$PhoneType
    )
    
    if (-not [string]::IsNullOrWhiteSpace($PhoneType)) {
        return "$PhoneNumber ($PhoneType)"
    }
    return $PhoneNumber
}

<#
.SYNOPSIS
    Adds entity change rows to CSV data using entity-specific formatting rules.

.DESCRIPTION
    Generic function that handles Added, Modified, and Removed changes for any entity type
    (Email, Phone, Address, Relationship). Uses entity type to determine proper formatting,
    ID field names, and display values.

.PARAMETER EntityType
    Type of entity: Email, Phone, Address, or Relationship
#>
function Add-EntityChanges {
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyCollection()]
        [System.Collections.Generic.List[PSCustomObject]]$CsvData,
        
        [Parameter(Mandatory = $true)]
        [hashtable]$BaseData,
        
        [Parameter(Mandatory = $true)]
        [ValidateSet('Email', 'Phone', 'Address', 'Relationship')]
        [string]$EntityType,
        
        [Parameter(Mandatory = $false)]
        $Changes
    )
    
    if (-not $Changes) { return }
    
    # Entity-specific configuration
    $config = Get-EntityConfig -EntityType $EntityType
    
    # Process Added changes
    if ($Changes.Added) {
        foreach ($item in $Changes.Added) {
            $recordId = Get-PropertyValue $item $config.IdField
            $displayValue = & $config.FormatValue $item
            
            $changeData = @{
                ChangeCategory = 'Updated'
                ChangeType = "$($EntityType)Added"
                Field = $config.FieldName
                OldValue = ''
                NewValue = $displayValue
                RecordID = $recordId
                RecordIDType = if ($recordId) { $config.IdField } else { '' }
            }
            
            # Add StudentNumbers for relationships
            if ($EntityType -eq 'Relationship' -and $item.StudentNumber) {
                $changeData['StudentNumbers'] = $item.StudentNumber
            }
            
            $CsvData.Add((New-CsvRow -BaseData $BaseData -ChangeData $changeData))
        }
    }
    
    # Process Modified changes
    if ($Changes.Modified) {
        foreach ($itemChange in $Changes.Modified) {
            # Get RecordID from the appropriate source based on entity structure
            $recordId = & $config.GetRecordId $itemChange
            
            foreach ($change in $itemChange.Changes) {
                $changeData = @{
                    ChangeCategory = 'Updated'
                    ChangeType = "$($EntityType)Modified"
                    Field = "$($EntityType).$($change.Field)"
                    OldValue = $change.OldValue
                    NewValue = $change.NewValue
                    RecordID = $recordId
                    RecordIDType = if ($recordId) { $config.IdField } else { '' }
                }
                
                # Add StudentNumbers for relationships
                if ($EntityType -eq 'Relationship') {
                    $changeData['StudentNumbers'] = Get-PropertyValue $itemChange 'StudentNumber'
                }
                
                $CsvData.Add((New-CsvRow -BaseData $BaseData -ChangeData $changeData))
            }
        }
    }
    
    # Process Removed changes
    if ($Changes.Removed) {
        foreach ($item in $Changes.Removed) {
            $recordId = Get-PropertyValue $item $config.IdField
            $displayValue = & $config.FormatValue $item
            
            $changeData = @{
                ChangeCategory = 'Updated'
                ChangeType = "$($EntityType)Removed"
                Field = $config.FieldName
                OldValue = $displayValue
                NewValue = ''
                RecordID = $recordId
                RecordIDType = if ($recordId) { $config.IdField } else { '' }
            }
            
            # Add StudentNumbers for relationships
            if ($EntityType -eq 'Relationship' -and $item.StudentNumber) {
                $changeData['StudentNumbers'] = $item.StudentNumber
            }
            
            $CsvData.Add((New-CsvRow -BaseData $BaseData -ChangeData $changeData))
        }
    }
}

<#
.SYNOPSIS
    Gets entity-specific configuration for formatting and ID handling.
#>
function Get-EntityConfig {
    param(
        [Parameter(Mandatory = $true)]
        [ValidateSet('Email', 'Phone', 'Address', 'Relationship')]
        [string]$EntityType
    )
    
    $configs = @{
        Email = @{
            IdField = 'EmailAddressID'
            FieldName = 'EmailAddress'
            FormatValue = { param($item) return $item.EmailAddress }
            GetRecordId = { param($item) 
                # For Modified items, ID is in OldEmail._id
                if ($item.OldEmail._id) { return $item.OldEmail._id }
                return Get-PropertyValue $item 'EmailAddressID'
            }
        }
        Phone = @{
            IdField = 'PhoneNumberID'
            FieldName = 'PhoneNumber'
            FormatValue = { param($item) return Format-PhoneDisplay -PhoneNumber $item.PhoneNumber -PhoneType $item.PhoneType }
            GetRecordId = { param($item) if ($item.OldPhone._id) { return $item.OldPhone._id } return Get-PropertyValue $item 'PhoneNumberID'}
        }
        Address = @{
            IdField = 'AddressID'
            FieldName = 'Address'
            FormatValue = { 
                param($item)
                # Use DisplayAddress if available, otherwise build from Address object properties
                if ($item.DisplayAddress) {
                    return $item.DisplayAddress
                }
                # Fallback to building from nested Address object
                $addr = if ($item.Address) { $item.Address } else { $item }
                $street = if ($addr.Street) { $addr.Street } else { $addr.address_street }
                $city = if ($addr.City) { $addr.City } else { $addr.address_city }
                $state = if ($addr.State) { $addr.State } else { $addr.address_state }
                $postal = if ($addr.PostalCode) { $addr.PostalCode } else { $addr.address_postalcode }
                return "$street, $city $state $postal"
            }
            GetRecordId = { param($item) if ($item.OldAddress._id) { return $item.OldAddress._id } return Get-PropertyValue $item 'AddressID'}
        }
        Relationship = @{
            IdField = 'StudentContactID'
            FieldName = 'Relationship'
            FormatValue = { param($item) return "$($item.RelationshipType) to $($item.StudentName) (#$($item.StudentNumber))" }
            GetRecordId = { param($item) if ($item.OldRelationship._id) { return $item.OldRelationship._id } return Get-PropertyValue $item 'StudentContactID'}
        }
    }
    
    return $configs[$EntityType]
}

#endregion
